### ISSUE TITLE
Spanish to Japanese

### ISSUE THREAD

**Issue by Adolfiux** [HRNPH/AIwaifu#13]
Is there a way to use Spanish instead of English, I recently setup the code, I will be trying to do it but any help on this would be awesome.

**Comment by HRNPH** [comment]
You mean prompting in Spanish and getting the Spanish answer right?
It is possible using the Machine Translation Model(NLLB in this case) to translate prompt into English before letting the Language Model Process it

**Comment by HRNPH** [comment]
This is an interesting suggestion for prompting in another language, I'll open the Issue for
"Multilingual Prompting" soon then
