### ISSUE TITLE
ERROR install requirements

### ISSUE THREAD

**Issue by Abbadon999** [HRNPH/AIwaifu#20]
I can't install your bot, I'm stuck on the first step of the installation
First `pip install -t ./requirements.txt` gives an error - `ERROR: Target path exists but is not a directory, will not continue.`

Secondly, I would like more detailed instructions about building as I honestly don't know what to do next. For example is it necessary to insert API or maybe to change input language?

**Comment by HRNPH** [comment]
oh sorry it's -r flag not -t flag

**Comment by HRNPH** [comment]
pip install -r ./requirements.txt

**Comment by HRNPH** [comment]
I've already updated the typo in README b81150735366ab8f94af98f526c41c4cfc580169
Try follow it again if it worked (Please notice me if it do work) so I can closed this Issue at ease

**Comment by Abbadon999** [comment]
Okay, thanks for the explanation, but I still can't install the libraries, because I can't install `pyopenjtalk-0.3.0`.
About the `-r` flag, I forgot to write that I already tried it and it gave me an error just because of `pyopenjtalk-0.3.0`.
I also tried installing pyopenjtalk via `pip install --no-binary :all: pyopenjtalk==0.3.0` using `pip install cython numpy setuptools wheel` but that doesn't help...

**Comment by Adolfiux** [comment]
You need to install Visual Studio and Visual Studio Build Tools. The trick is to select the C++ tools during the installation of both. After that, you need to open a CMake project in Visual Studio so that the project information displays the location of cmake.exe. Then, you need to add this location to the system's path without including the actual cmake.exe file, only the path where it is located. Once you do this, you should be able to install that and other packages without any issues.

**Comment by HRNPH** [comment]
> You need to install Visual Studio and Visual Studio Build Tools. The trick is to select the C++ tools during the installation of both. After that, you need to open a CMake project in Visual Studio so that the project information displays the location of cmake.exe. Then, you need to add this location to the system's path without including the actual cmake.exe file, only the path where it is located. Once you do this, you should be able to install that and other packages without any issues.

0h yeah I forgot to include that thx!

**Comment by HRNPH** [comment]
I've already updated the document 

> Okay, thanks for the explanation, but I still can't install the libraries, because I can't install `pyopenjtalk-0.3.0`. About the `-r` flag, I forgot to write that I already tried it and it gave me an error just because of `pyopenjtalk-0.3.0`. I also tried installing pyopenjtalk via `pip install --no-binary :all: pyopenjtalk==0.3.0` using `pip install cython numpy setuptools wheel` but that doesn't help...

Can you capture the screenshot of an error?

**Comment by ponmak** [comment]
>Collecting pyopenjtalk==0.3.0
  Using cached pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

>× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]

>note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
I have a same issue, Here a some screenshot.

**Comment by Abbadon999** [comment]
@Adolfiux 
I already have Visual Studio installed, is there any way I can install C++ and all the features you mentioned earlier into it or do I need to reinstall it?

**Comment by HRNPH** [comment]
first off all try check if you have Cmake install
```bash
# open CMD or Terminal and type
cmake
```
(you wouldn't have it but just to be sure)
Then referring to [this issue in pyopenjtalk](https://github.com/r9y9/pyopenjtalk/issues/30#issuecomment-1454952624)
you need to install [Cmake](https://cmake.org/download/) just download the installer and set it up

**Comment by HRNPH** [comment]
what about these guys? do you have it installed
```
gcc (g++)
cmake
cython
```

**Comment by ponmak** [comment]
![image](https://user-images.githubusercontent.com/67944900/231791548-7df90c32-16da-4f71-a8e8-d390157aa3a4.png)
Thx I got it

**Comment by HRNPH** [comment]
It seems that @ponmak error and @Abbadon999 error were different so can I request you to reproduce the error and send us the error log?

**Comment by ponmak** [comment]
@Abbadon999 
>I already have Visual Studio installed, is there any way I can install C++ and all the features you mentioned earlier into it or do I need to reinstall it?

1. Open your Visual Studio Installer. Go to `Modify`
![image](https://user-images.githubusercontent.com/67944900/231788161-1f93fbf5-6a81-4d15-8522-5a3b98662022.png)
2.Click to `desktop development with c++`  and install
![image](https://user-images.githubusercontent.com/67944900/231793118-7d4c1827-bb53-45a4-b9a0-71fe49ca132d.png)
![image](https://user-images.githubusercontent.com/67944900/231793532-12857018-1503-4bd6-8837-a16ba9107fb9.png)

Maybe it helped

**Comment by Abbadon999** [comment]
Hooray, I finally installed "pyopenjtalk-0.3.0", but now I have a new error with "numpy", I guess I should try to change the version, because apparently it conflicts with other packages.
![image](https://user-images.githubusercontent.com/42169608/231797133-9a0435b3-38dd-4655-8fca-ee20303b3964.png)

**Comment by Abbadon999** [comment]
**Edited:**
So, I reinstalled the files and "1374_epochs.pth" seems to be found, but now a new error....
```
PS F:\AI-Waify\NICE\AIwaifu> python ./main.py
Initializing... Dependencies
Traceback (most recent call last):
  File "F:\AI-Waify\NICE\AIwaifu\main.py", line 3, in <module>
    from anime_tts.custom_inference import tts # text to speech from huggingface
  File "F:\AI-Waify\NICE\AIwaifu\anime_tts\custom_inference.py", line 7, in <module>
    net_g_ms, hps = infer.load_model(config_json, pth_path)
  File "F:\AI-Waify\NICE\AIwaifu\anime_tts\infer.py", line 61, in load_model
    _ = utils.load_checkpoint(pth_path, net_g_ms)
  File "F:\AI-Waify\NICE\AIwaifu\anime_tts\utils.py", line 41, in load_checkpoint
    checkpoint_dict = load(checkpoint_path, map_location='cpu')
  File "C:\Users\valer\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\valer\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by HRNPH** [comment]
@Abbadon999 is it Working?

**Comment by HRNPH** [comment]
well Read an exception "Exception: Please start VTube Studio and enable the public API in the settings"
basically just follow next instruction before start the script

**Comment by HRNPH** [comment]
just follow instruction given in the readme you need to install plugin by lua lucky

**Comment by Abbadon999** [comment]
Thanks for your help, I think this can be closed)

**Comment by HRNPH** [comment]
There'll be update soon in this months :DD

**Comment by Sylensar** [comment]
@HRNPH Just got Cmake.

**Comment by HRNPH** [comment]
> @HRNPH Just got Cmake.

if you're on windows don't forget to install C++ Dev SDK

after that
proceed with the installation

**Comment by Sylensar** [comment]
@HRNPH im running the 

pip install pyopenjtalk

command correct?

**Comment by HRNPH** [comment]
> @HRNPH im running the 
> 
> pip install pyopenjtalk
> 
> command correct?

yeah

**Comment by HRNPH** [comment]
> @HRNPH im running the 
> 
> pip install pyopenjtalk
> 
> command correct?

yeah
