### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by andri-jpg** [HRNPH/AIwaifu#29]
Did you forget something during a recent push commit? I got a traceback like this :

(base) PS D:\AIwaifu> python api_inference_server.py
Traceback (most recent call last):
  File "D:\AIwaifu\api_inference_server.py", line 3, in <module>
    from anime_tts.custom_inference import tts # text to speech from huggingface
ModuleNotFoundError: No module named 'anime_tts.custom_inference'
(base) PS D:\AIwaifu>

**Comment by HRNPH** [comment]
oh sorry I didn't fix that line yet wait a min

**Comment by andri-jpg** [comment]
I've done a pull request in that section

**Comment by HRNPH** [comment]
merged #30
