### ISSUE TITLE
ModuleNotFoundError: No module named 'AIVoifu.voice_conversion.Sovits.monotonic_align.monotonic_align.core'

### ISSUE THREAD

**Issue by T9es** [HRNPH/AIwaifu#35]
![image](https://user-images.githubusercontent.com/107748212/235263765-43d99103-b619-43ba-933b-6b853d53bd92.png)

It's late at night here for me, don't have the mental power to chew through this one alone. I've removed the numpy version from requirements to fix some install issues. Don't know/Can't check if the issue is regarding this. My internet connection is really bad rn, so don't want to re-install a bunch of stuff as this can take HOURS, even small files, unless it's mandatory

**Comment by HRNPH** [comment]
I think you need to build monotolic align

**Comment by T9es** [comment]
Huh, I actually did go through the readme and did the step, however, now after doing it again it works... god I need some sleep, me being tired might have been the reason, might have skipped something, sorry to bother

**Comment by HRNPH** [comment]
yeah nevermind, after you've used it please give some feedback for improvement In  discussion so we can make this better together

**Comment by Sylensar** [comment]
Im getting a error when entering that command.

**Comment by HRNPH** [comment]
@Sylensar 
what error?
please show the picture, Log, or explanation
you should access the "AIVoifu" folder then using the build command provided
please open new issue in case it's the new error
