### ISSUE TITLE
Suggestion for TTS

### ISSUE THREAD

**Issue by MayiVT** [HRNPH/AIwaifu#37]
My suggestion is to add the model have support for tts programs like [VoiceVox](https://github.com/VOICEVOX) or [tortoise](https://github.com/neonbjb/tortoise-tts)

These will add a better TTS and more customitzation to it.

**Comment by MahdeenSky** [comment]
actually, https://github.com/RVC-Boss/GPT-SoVITS would be much better

**Comment by HRNPH** [comment]
VoiceVox was cool but low customizability, Tortoise was ditched
After taking a look at SoVITS, I Made decision to use implementation following [RVC](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/en/README.en.md) instead as it still get maintained.

Thanks,
