### ISSUE TITLE
can't import Sovits Monotolic Align

### ISSUE THREAD

**Issue by Sylensar** [HRNPH/AIwaifu#41]
Initializing... Dependencies
Traceback (most recent call last):
  File "d:\ainy4\AIwaifu-master\main.py", line 19, in <module>
    from AIVoifu.voice_conversion import vc_inference as vc
  File "d:\ainy4\AIwaifu-master\AIVoifu\voice_conversion\vc_inference.py", line 13, in <module>
    from .Sovits.data_utils import UnitAudioLoader, UnitAudioCollate
  File "d:\ainy4\AIwaifu-master\AIVoifu\voice_conversion\Sovits\data_utils.py", line 10, in <module>
    from .models import SynthesizerTrn
  File "d:\ainy4\AIwaifu-master\AIVoifu\voice_conversion\Sovits\models.py", line 10, in <module>
    from . import monotonic_align
  File "d:\ainy4\AIwaifu-master\AIVoifu\voice_conversion\Sovits\monotonic_align\__init__.py", line 3, in <module>
    from .monotonic_align.core import maximum_path_c
ModuleNotFoundError: No module named 'AIVoifu.voice_conversion.Sovits.monotonic_align.monotonic_align.core'
PS D:\ainy4> pip install AIVoifu.voice_conversion.Sovits.monotonic_align.monotonic_align.core
ERROR: Could not find a version that satisfies the requirement AIVoifu.voice_conversion.Sovits.monotonic_align.monotonic_align.core (from versions: none)
ERROR: No matching distribution found for AIVoifu.voice_conversion.Sovits.monotonic_align.monotonic_align.core

**Comment by HRNPH** [comment]
As for this, you need to build Sovits.monotonic_align.monotonic_align.core
referring to this Issue #35 

This should work (if you cd correctly)
```bash
cd "d:/ainy4/AIwaifu-master/AIVoifu/voice_conversion/Sovits/monotonic_align"
python setup.py build_ext --inplace
```

**Comment by Sylensar** [comment]
@HRNPH 

**C:\Users\oung\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'D:\\Rainy4\\AIwaifu\\setup.py': [Errno 2] No such file or directory
PS D:\Rainy4\AIwaifu> cd "d:/Rainy4/AIwaifu-master/AIVoifu/voice_conversion/Sovits/monotonic_align"
>> python setup.py build_ext --inplace
cd : Cannot find path 'D:\Rainy4\AIwaifu-master\AIVoifu\voice_conversion\Sovits\monotonic_align' because it does not exist.
At line:1 char:1
+ cd "d:/Rainy4/AIwaifu-master/AIVoifu/voice_conversion/Sovits/monotoni ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Rainy4\AIwai...monotonic_align:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
 
C:\Users\Young\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'D:\\Rainy4\\AIwaifu\\setup.py': [Errno 2] No such file or directory**

**Comment by Sylensar** [comment]
@HRNPH 

C:\Users\oung\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'D:\\ainy4\\AIwaifu\\setup.py': [Errno 2] No such file or directory
PS D:\ainy4\AIwaifu> cd "d:/Rainy4/AIwaifu-master/AIVoifu/voice_conversion/Sovits/monotonic_align"
>> python setup.py build_ext --inplace
cd : Cannot find path 'D:\ainy4\AIwaifu-master\AIVoifu\voice_conversion\Sovits\monotonic_align' because it does not exist.
At line:1 char:1
+ cd "d:/ainy4/AIwaifu-master/AIVoifu/voice_conversion/Sovits/monotoni ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\ainy4\AIwai...monotonic_align:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
 
C:\Users\oung\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'D:\\ainy4\\AIwaifu\\setup.py': [Errno 2] No such file or directory

**Comment by HRNPH** [comment]
please try 'cd' into the correct directory 
and get into Sovits folder first

then use

```bash
dir
```
to check for files and directories

**Comment by Sylensar** [comment]
cd D:\ainy4\AIwaifu\AIVoifu\voice_conversion\Sovits

@HRNPH Is this correct?

**Comment by HRNPH** [comment]
try cd in
and use
```bash
pwd
```
to see if you're in the correct path

**Comment by Sylensar** [comment]
@HRNPH Okay It says im in PS D:\ainy4\AIwaifu\AIVoifu\voice_conversion\Sovits> 

should be correct

**Comment by HRNPH** [comment]
> @HRNPH Okay It says im in PS D:\ainy4\AIwaifu\AIVoifu\voice_conversion\Sovits> 
> 
> should be correct

Ok then try using
```bash
dir
```

check all the files and folders existed

**Comment by Sylensar** [comment]
@HRNPH yup i see the list.

**Comment by HRNPH** [comment]
> @HRNPH yup i see the list.
> 

try running build command

**Comment by Sylensar** [comment]
This is the correct list right?    

 Directory: D:\ainy4\AIwaifu\AIVoifu\voice_conversion\Sovits


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         5/24/2023   1:47 PM                assets
d-----         5/24/2023   1:47 PM                configs
d-----         5/24/2023   1:47 PM                examples
d-----         5/24/2023   1:47 PM                filelists
d-----         5/24/2023   1:47 PM                JDC
d-----         5/27/2023   6:30 PM                monotonic_align
d-----         5/27/2023   6:18 PM                __pycache__
------         5/24/2023   1:47 PM           4778 commons.py
------         5/24/2023   1:47 PM          12601 data_utils.py
------         5/24/2023   1:47 PM           1069 LICENSE
------         5/24/2023   1:47 PM           1353 losses.py
------         5/24/2023   1:47 PM           4143 mel_processing.py
------         5/24/2023   1:47 PM          21125 models.py
------         5/24/2023   1:47 PM          15107 modules.py
------         5/24/2023   1:47 PM           4685 README.md
------         5/24/2023   1:47 PM             95 requirements.txt
------         5/24/2023   1:47 PM          13166 train.py
------         5/24/2023   1:47 PM          12101 train_ms.py
------         5/24/2023   1:47 PM           8490 transforms.py
------         5/24/2023   1:47 PM           7390 utils.py

**Comment by HRNPH** [comment]
Yeah Legit, Now build it

**Comment by Sylensar** [comment]
Upon pasting python setup.py build_ext --inplace I get 

can't open file 'D:\\ainy4\\AIwaifu\\AIVoifu\\voice_conversion\\Sovits\\setup.py': [Errno 2] No such file or directory
PS D:\ainy4\AIwaifu\AIVoifu\voice_conversion\Sovits>  again

**Comment by HRNPH** [comment]
wait wait 
please cd into the monotolic_align folder first

**Comment by Sylensar** [comment]
I think im having a problem correctly install pyopenjtalk now @HRNPH Tells me 

Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by HRNPH** [comment]
> I think im having a problem correctly install pyopenjtalk now @HRNPH Tells me 
> 
> Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.


as for this please read this issue 
#20

**Comment by EmiDaDuck** [comment]
I am missing the whole folders Sovits/monotonic_align
