### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Sylensar** [HRNPH/AIwaifu#42]
I thought I was in the clear and ran into this.

**Initializing... Dependencies
Loading Waifu Vocal Pipeline...
Using model d:\Rainy4\AIwaifu\AIVoifu\voice_conversion/models\base_model.pth
Using cache found in C:\Users\oung/.cache\torch\hub\bshall_hubert_main
Downloading: "https://github.com/bshall/hubert/releases/download/v0.1/hubert-soft-0d54a1f4.pt" to C:\Users\oung/.cache\torch\hub\checkpoints\hubert-soft-0d54a1f4.pt
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 361M/361M [00:14<00:00, 25.4MB/s]
INFO:root:Loaded checkpoint 'd:\Rainy4\AIwaifu\AIVoifu\voice_conversion/models\base_model.pth' (iteration 474)
Loaded Waifu Vocal Pipeline
Initializing... Vtube Studio
Traceback (most recent call last):
  File "d:\Rainy4\AIwaifu\main.py", line 39, in <module>
    waifu = Char_control(port=8001, plugin_name='MyBitchIsAI', plugin_developer='HRNPH')
  File "d:\Rainy4\AIwaifu\vtube_studio.py", line 89, in __init__
    super().__init__(plugin_name, plugin_developer, port)
  File "d:\Rainy4\AIwaifu\vtube_studio.py", line 11, in __init__
    self.websocket = websocket.WebSocket()
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'**

**Comment by Sylensar** [comment]
Fixed it.

**Comment by HRNPH** [comment]
Please be sure to describe what you encounter and how you fixed it
to help others that may encounter the same issue
