### ISSUE TITLE
Exeption Occured

### ISSUE THREAD

**Issue by Sylensar** [HRNPH/AIwaifu#43]
Initializing... Dependencies
Loading Waifu Vocal Pipeline...
Using model d:\Rainy4\AIwaifu\AIVoifu\voice_conversion/models\base_model.pth
Using cache found in C:\Users\Young/.cache\torch\hub\bshall_hubert_main
Loaded Waifu Vocal Pipeline
Initializing... Vtube Studio
Authenticated with VTube Studio...
Authentication token: 442a9155b175589dceb4db0ce26da5cff658d11f1658a5c2adf39f96e69ead5c
Status: {'apiName': 'VTubeStudioPublicAPI', 'apiVersion': '1.0', 'timestamp': 1685233452526, 'messageType': 'AuthenticationTokenResponse', 'requestID': 'TestInit', 'data': {'authenticationToken': '442a9155b175589dceb4db0ce26da5cff658d11f1658a5c2adf39f96e69ead5c'}}
Initialized
You: Hello there.
--------- Exception Occured ---------
if you have run the server on different device, please specify the ip address of the server with the port
Example: http://192.168.1.112:8267 or leave it blank to use localhost
***please specify the ip address of the server with the port*** at:
*Line 52: HTTPConnectionPool(host='localhost', port=8267): Max retries exceeded with url: /waifuapi?command=chat&data=Hello+there. (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000179D0833310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Idk if Im starting the server correctly or not.

**Comment by HRNPH** [comment]
Try Checking The Vtuber Studio API Port if it was opened!

**Comment by Sylensar** [comment]
Yes @HRNPH the Start API (allow plugins) is activated. Do I have to change the port from 8001 ?

**Comment by HRNPH** [comment]
port should be the same as the error code below which is 8267
try changing it

**Comment by Sylensar** [comment]
@HRNPH I dont even get the popup prompt anymore in VTube Studio

Traceback (most recent call last):
  File "d:\Rainy4\AIwaifu\main.py", line 39, in <module>
    waifu = Char_control(port=8001, plugin_name='MyBitchIsAI', plugin_developer='HRNPH')
  File "d:\Rainy4\AIwaifu\vtube_studio.py", line 89, in __init__
    super().__init__(plugin_name, plugin_developer, port)
  File "d:\Rainy4\AIwaifu\vtube_studio.py", line 23, in __init__
    auth_status = self.auth()
  File "d:\Rainy4\AIwaifu\vtube_studio.py", line 34, in auth
    result = self.send("AuthenticationTokenRequest", msg)
  File "d:\Rainy4\AIwaifu\vtube_studio.py", line 60, in send
    raise Exception("Please start VTube Studio and enable the public API in the settings.")
Exception: Please start VTube Studio and enable the public API in the settings.

**Comment by Sylensar** [comment]
@HRNPH Do I change it on line 39 too?

**Comment by Sylensar** [comment]
Got it to pop up by changing line 39. now im getting this 

Traceback (most recent call last):
  File "d:\Rainy4\AIwaifu\main.py", line 79, in <module>
    answer, japanese_answer = answer[0], answer[1]
IndexError: list index out of range

sheesh

**Comment by HRNPH** [comment]
this one could actually be a bug
I need to fix this by myself today

if you want to try solving it
you can try printing out the list value

**Comment by Sylensar** [comment]
# ----------- Create Response --------------------------
    answer = chat(con) # send message to api
    answer = answer.split('<split_token>')
    answer, japanese_answer = answer[0], answer[1]
    answer.replace('Lilia:', '') # remove name from answer

where it says Asnwer.split? How I log it?

**Comment by HRNPH** [comment]
do print answers after that line

**Comment by Sylensar** [comment]
# ----------- Create Response --------------------------
    answer = chat(con) # send message to api
    answer = answer.split('<split_token>') print answers
    answer, japanese_answer = answer[0], answer[1]
    answer.replace('Lilia:', '') # remove name from answer

like so? Or you meant under it?

**Comment by HRNPH** [comment]
```python
answer = chat(con) # send message to api
answer = answer.split('<split_token>')
print(answer) # like this
answer, japanese_answer = answer[0], answer[1]
answer.replace('Lilia:', '') # remove name from answer
```
