### ISSUE TITLE
ERROR: Cannot install

### ISSUE THREAD

**Issue by W4RI0CK** [HRNPH/AIwaifu#45]
ERROR: Cannot install -r ./requirements.txt (line 18), -r ./requirements.txt (line 35), -r ./requirements.txt (line 7), numba==0.56.4 and numpy==1.24.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.24.2
    blis 0.7.9 depends on numpy>=1.15.0
    datasets 2.10.1 depends on numpy>=1.17
    librosa 0.10.0.post2 depends on numpy!=1.22.0, !=1.22.1, !=1.22.2 and >=1.20.3
    numba 0.56.4 depends on numpy<1.24 and >=1.18

**Comment by HRNPH** [comment]
The config was now edited
can you try pulling it and install again?

**Comment by W4RI0CK** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 3.33.1 requires huggingface-hub>=0.14.0, but you have huggingface-hub 0.13.3 which is incompatible.
httpx 0.13.3 requires idna==2.*, but you have idna 3.4 which is incompatible.
onnxruntime-gpu 1.15.0 requires numpy>=1.21.6, but you have numpy 1.20.3 which is incompatible.
torchcrepe 0.0.18 requires librosa==0.9.1, but you have librosa 0.10.0.post2 which is incompatible.
unidic 1.1.0 requires wasabi<1.0.0,>=0.6.0, but you have wasabi 1.1.1 which is incompatible.
