### ISSUE TITLE
LNK2001 error while installing monotonic_align module

### ISSUE THREAD

**Issue by HLsosung** [HRNPH/AIwaifu#61]
how can i solve this problem? already installed build tools, cython,gcc(++),cmake and dev C++ but i can't solve this LNK2001 error 

   Creating library build\temp.win32-cpython-310\Release\core.cp310-win_amd64.lib and object build\temp.win32-cpython-310\Release\core.cp310-win_amd64.exp
core.obj : error LNK2001: unresolved external symbol __imp__PyBaseObject_Type
core.obj : error LNK2001: unresolved external symbol __imp__PyGC_Enable
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_BufferError
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_SetAttr
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_InternFromString
core.obj : error LNK2001: unresolved external symbol __imp__PyCFunction_Type
core.obj : error LNK2001: unresolved external symbol __imp__PyOS_snprintf
core.obj : error LNK2001: unresolved external symbol __imp__PyThreadState_Get
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_SetObject
core.obj : error LNK2001: unresolved external symbol __imp__PyCode_NewEmpty
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_GivenExceptionMatches
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsUnsignedLong
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_Malloc
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_WarnEx
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_RuntimeWarning
core.obj : error LNK2001: unresolved external symbol __imp__PyFrame_New
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsSsize_t
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_DeprecationWarning
core.obj : error LNK2001: unresolved external symbol __imp__Py_LeaveRecursiveCall
core.obj : error LNK2001: unresolved external symbol __imp__PySlice_Type
core.obj : error LNK2001: unresolved external symbol __imp___PyLong_AsByteArray
core.obj : error LNK2001: unresolved external symbol __imp__PyImport_ImportModuleLevelObject
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_NormalizeException
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_Occurred
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromSsize_t
core.obj : error LNK2001: unresolved external symbol __imp__PyNumber_Remainder
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GenericGetAttr
core.obj : error LNK2001: unresolved external symbol __imp__PyTraceBack_Here
core.obj : error LNK2001: unresolved external symbol __imp__PyEval_SaveThread
core.obj : error LNK2001: unresolved external symbol __imp___PyThreadState_UncheckedGet
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_RuntimeError
core.obj : error LNK2001: unresolved external symbol __imp__PyMethod_New
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_SetAttrString
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromLong
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GC_UnTrack
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_Hash
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Concat
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_UnboundLocalError
core.obj : error LNK2001: unresolved external symbol __imp__PyInterpreterState_GetID
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromUnsignedLongLong
core.obj : error LNK2001: unresolved external symbol __imp__Py_GetVersion
core.obj : error LNK2001: unresolved external symbol __imp__PyThread_allocate_lock
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetAttr
core.obj : error LNK2001: unresolved external symbol __imp__PyModule_GetName
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_FromOrdinal
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsUnsignedLongLong
core.obj : error LNK2001: unresolved external symbol __imp__PyBytes_FromString
core.obj : error LNK2001: unresolved external symbol __imp__PyGILState_Release
core.obj : error LNK2001: unresolved external symbol __imp___Py_NoneStruct
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsLongLong
core.obj : error LNK2001: unresolved external symbol __imp__PyTuple_New
core.obj : error LNK2001: unresolved external symbol __imp__PySequence_Contains
core.obj : error LNK2001: unresolved external symbol __imp__PyDict_SetItemString
core.obj : error LNK2001: unresolved external symbol __imp__PyDict_Size
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromLongLong
core.obj : error LNK2001: unresolved external symbol __imp__PyGC_Disable
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_AttributeError
core.obj : error LNK2001: unresolved external symbol __imp__PyTuple_GetSlice
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_New
core.obj : error LNK2001: unresolved external symbol __imp__PyNumber_Multiply
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_SetString
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_ZeroDivisionError
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetIter
core.obj : error LNK2001: unresolved external symbol __imp__PyNumber_Add
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_WarnFormat
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_ValueError
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromUnsignedLong
core.obj : error LNK2001: unresolved external symbol __imp__PyDict_Next
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_Format
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_RichCompare
core.obj : error LNK2001: unresolved external symbol __imp__PyTuple_Type
core.obj : error LNK2001: unresolved external symbol __imp___Py_FalseStruct
core.obj : error LNK2001: unresolved external symbol __imp__PyImport_GetModule
core.obj : error LNK2001: unresolved external symbol __imp__PyNumber_InPlaceAdd
core.obj : error LNK2001: unresolved external symbol __imp__PyFloat_Type
core.obj : error LNK2001: unresolved external symbol __imp___PyLong_FromByteArray
core.obj : error LNK2001: unresolved external symbol __imp__PyModule_NewObject
core.obj : error LNK2001: unresolved external symbol __imp__PyMethod_Type
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_Type
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_Restore
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Join
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_OverflowError
core.obj : error LNK2001: unresolved external symbol __imp__PyCode_NewWithPosOnlyArgs
core.obj : error LNK2001: unresolved external symbol __imp___Py_Dealloc
core.obj : error LNK2001: unresolved external symbol __imp__PyTuple_GetItem
core.obj : error LNK2001: unresolved external symbol __imp__PyImport_GetModuleDict
core.obj : error LNK2001: unresolved external symbol __imp__PyModule_GetDict
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_Format
core.obj : error LNK2001: unresolved external symbol __imp__PySequence_GetSlice
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_Free
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_ExceptionMatches
core.obj : error LNK2001: unresolved external symbol __imp__PyCapsule_GetPointer
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GC_Del
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_Fetch
core.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsLong
core.obj : error LNK2001: unresolved external symbol __imp__PyDescr_IsData
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_ClearWeakRefs
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_Not
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_AsUTF8
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_FromFormat
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetBuffer
core.obj : error LNK2001: unresolved external symbol __imp__PyNumber_InPlaceMultiply
core.obj : error LNK2001: unresolved external symbol __imp__PyList_New
core.obj : error LNK2001: unresolved external symbol __imp__PySlice_New
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GC_IsFinalized
core.obj : error LNK2001: unresolved external symbol __imp__PyImport_AddModule
core.obj : error LNK2001: unresolved external symbol __imp__PyType_Ready
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetAttrString
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_Clear
core.obj : error LNK2001: unresolved external symbol __imp__PyList_Append
core.obj : error LNK2001: unresolved external symbol __imp__PyBytes_Type
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_RichCompareBool
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Decode
core.obj : error LNK2001: unresolved external symbol __imp__PyException_SetTraceback
core.obj : error LNK2001: unresolved external symbol __imp__PyCapsule_New
core.obj : error LNK2001: unresolved external symbol __imp___PyObject_GenericGetAttrWithDict
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_VectorcallDict
core.obj : error LNK2001: unresolved external symbol __imp__PyDict_SetItem
core.obj : error LNK2001: unresolved external symbol __imp__PyDict_New
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Type
core.obj : error LNK2001: unresolved external symbol __imp__PyThread_free_lock
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_CallFinalizerFromDealloc
core.obj : error LNK2001: unresolved external symbol __imp___PyDict_GetItem_KnownHash
core.obj : error LNK2001: unresolved external symbol __imp__PyNumber_Index
core.obj : error LNK2001: unresolved external symbol __imp__PyMem_Free
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_StopIteration
core.obj : error LNK2001: unresolved external symbol __imp__PyCMethod_New
core.obj : error LNK2001: unresolved external symbol __imp__PyList_Type
core.obj : error LNK2001: unresolved external symbol __imp__PyErr_NoMemory
core.obj : error LNK2001: unresolved external symbol __imp__PyDict_GetItemString
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetItem
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_CallObject
core.obj : error LNK2001: unresolved external symbol __imp__PyModuleDef_Init
core.obj : error LNK2001: unresolved external symbol __imp__PyIndex_Check
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_GC_Track
core.obj : error LNK2001: unresolved external symbol __imp__PyBytes_FromStringAndSize
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_NotImplementedError
core.obj : error LNK2001: unresolved external symbol __imp__PyGILState_Ensure
core.obj : error LNK2001: unresolved external symbol __imp__PyDict_DelItem
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Compare
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_IsSubclass
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_TypeError
core.obj : error LNK2001: unresolved external symbol __imp__PyMem_Realloc
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_IsTrue
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_NameError
core.obj : error LNK2001: unresolved external symbol __imp__PyTuple_Pack
core.obj : error LNK2001: unresolved external symbol __imp__Py_OptimizeFlag
core.obj : error LNK2001: unresolved external symbol __imp___PyUnicode_Ready
core.obj : error LNK2001: unresolved external symbol __imp__PyMem_Malloc
core.obj : error LNK2001: unresolved external symbol __imp__PyList_AsTuple
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_IndexError
core.obj : error LNK2001: unresolved external symbol __imp__Py_EnterRecursiveCall
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_ImportError
core.obj : error LNK2001: unresolved external symbol __imp___Py_TrueStruct
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_SystemError
core.obj : error LNK2001: unresolved external symbol __imp___PyUnicode_FastCopyCharacters
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_SetItem
core.obj : error LNK2001: unresolved external symbol __imp___PyObject_GC_New
core.obj : error LNK2001: unresolved external symbol __imp__PyException_SetCause
core.obj : error LNK2001: unresolved external symbol __imp__PyType_Modified
core.obj : error LNK2001: unresolved external symbol __imp__PyTraceBack_Type
core.obj : error LNK2001: unresolved external symbol __imp__PyGILState_Check
core.obj : error LNK2001: unresolved external symbol __imp___Py_FatalErrorFunc
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_FromString
core.obj : error LNK2001: unresolved external symbol __imp___PyType_Lookup
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Format
core.obj : error LNK2001: unresolved external symbol __imp__PyBuffer_Release
core.obj : error LNK2001: unresolved external symbol __imp__PyObject_Call
core.obj : error LNK2001: unresolved external symbol __imp__PySequence_Tuple
core.obj : error LNK2001: unresolved external symbol __imp__PyEval_RestoreThread
core.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_FromStringAndSize
core.obj : error LNK2001: unresolved external symbol __imp__PyExc_ModuleNotFoundError
core.obj : error LNK2001: unresolved external symbol __imp___PyObject_GetDictPtr
build\lib.win32-cpython-310\monotonic_align\core.cp310-win_amd64.pyd : fatal error LNK1120: 173 unresolved externals
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x86\\link.exe' failed with exit code 1120

**Comment by HLsosung** [comment]
might be visual studio error. vs code can smoothy run the code

**Comment by HRNPH** [comment]
I see I usually ran via cli so I've never got these error
