### ISSUE TITLE
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'

### ISSUE THREAD

**Issue by MercyfulKing** [HRNPH/AIwaifu#67]
getting this error...and then the command window just closes

ERROR - 
Traceback (most recent call last):
  File "c:\Users\daf12\AIwaifu\AIwaifu\vtube_studio.py", line 126, in <module>
    waifu = Char_control()
  File "c:\Users\daf12\AIwaifu\AIwaifu\vtube_studio.py", line 90, in __init__
    super().__init__(plugin_name, plugin_developer, port)
  File "c:\Users\daf12\AIwaifu\AIwaifu\vtube_studio.py", line 12, in __init__
    self.websocket = websocket.WebSocket()
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'

CODE in vtube_studio.py
class MBIS_vtube:
    def __init__(self, plugin_name="MyBitchIsAi", plugin_developer='HRNPH', port=8001):
        self.websocket = websocket.WebSocket() ******this little mf right here needs something I'm guessing
        self.port = port
        self.plugin_name = plugin_name
        self.plugin_developer = plugin_developer 
        self.auth_token = None

**Comment by MercyfulKing** [comment]
I literally am just running the main.py and after it asks about downloading the new voice models it returns the error and closes. There was some info I found https://techoverflow.net/2021/02/06/how-to-fix-python-websocket-typeerror-__init__-missing-3-required-positional-arguments-environ-socket-and-rfile/
pip uninstall websocket
pip install websocket-client
but that didn't work either and returned the same error.

**Comment by MercyfulKing** [comment]
I feel like this the last hurdle and I can finally get this working. lol. The server thing runs and is open as well as vtube studio with allow allow plugins.

**Comment by HRNPH** [comment]
how did you solve it please share
I think the websocket issue is what
some of the users encounter as well
